export const CountriesData = [
  { label: "United States", value: "1" },
  { label: "Bahamas", value: "2" },
  { label: "Barbados", value: "3" },
  { label: "Anguilla", value: "4" },
  { label: "Antigua", value: "5" },
  { label: "British Virgin Islands", value: "6" },
  { label: "Cayman Islands", value: "7" },
  { label: "Bermuda", value: "8" },
  { label: "Turks and Caicos Islands", value: "9" },
  { label: "Jamaica", value: "10" },
  { label: "Montserrat", value: "11" },
  { label: "Sint Maarten", value: "12" },
  { label: "Saint Lucia", value: "13" },
  { label: "Dominica", value: "14" },
  { label: "Saint Vincent and the Grenadines", value: "15" },
  { label: "Dominican Republic", value: "16" },
  { label: "Trinidad and Tobago", value: "17" },
  { label: "Saint Kitts and Nevis", value: "18" },
  { label: "Egypt", value: "19" },
  { label: "Nigeria", value: "20" },
  { label: "South Sudan", value: "21" },
  { label: "Morocco", value: "22" },
  { label: "Algeria", value: "23" },
  { label: "Tunisia", value: "24" },
  { label: "Libya", value: "25" },
  { label: "Gambia", value: "26" },
  { label: "Senegal", value: "27" },
  { label: "Mauritania", value: "28" },
  { label: "Mali", value: "29" },
  { label: "Guinea", value: "30" },
  { label: "Ivory Coast", value: "31" },
  { label: "Burkina Faso", value: "32" },
  { label: "Niger", value: "33" },
  { label: "Togo", value: "34" },
  { label: "Canada", value: "35" },
  { label: "United Kingdom", value: "36" },
  { label: "Germany", value: "37" },
  { label: "France", value: "38" },
  { label: "Italy", value: "39" },
  { label: "Spain", value: "40" },
  { label: "Australia", value: "41" },
  { label: "Japan", value: "42" },
  { label: "China", value: "43" },
  { label: "Brazil", value: "44" },
  { label: "Mexico", value: "45" },
  { label: "Argentina", value: "46" },
];
